const links = {
  "AIDS Partnership Michigan": "http://www.aidspartnership.org/",
  "Adams Apple": "https:/www.facebook.com/adamsapple.mi/",
  Affirmations: "http://www.goaffirmations.org/",
  "Apartment Lounge": "http://www.apartmentlounge.net/",
  "Aut Bar": "https://www.facebook.com/a2autbar/",
  "Baton Show Lounge": "http://www.thebatonshowlounge.com/",
  "Body Zone Detroit":
    "https://www.metramagazine.com/hot-links/%20https://www.facebook.com/adamsapple.mi/",
  "Briggs Detroit": "https://www.facebook.com/briggsdetroit/",
  "": "",
  "": "",
  "": "",
  "": "",
  "": "",
  "": "",
  "": "",
  "": "",
  "": "",
  "": "",
  "": "",
  "": "",
  "": "",
  "": "",
  "": "",
  "": "",
  "": "",
  "": "",
  "": "",
  "": "",
  "": "",
  "": "",
  "": "",
  "": "",
  "": "",
  "": "",
  "": "",
};
